// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0e2olAFDpmsUhe_HKbEf3Hj1oRqp3Vk',
    appId: '1:74152208737:web:f7f550425792c59d463d20',
    messagingSenderId: '74152208737',
    projectId: 'filmin-7e708',
    authDomain: 'filmin-7e708.firebaseapp.com',
    storageBucket: 'filmin-7e708.firebasestorage.app',
    measurementId: 'G-SNNQ50CTGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1J-RadgCLktOhlbFM5U664_czJFqG1Ak',
    appId: '1:74152208737:android:6bf5e247a56686f8463d20',
    messagingSenderId: '74152208737',
    projectId: 'filmin-7e708',
    storageBucket: 'filmin-7e708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzepmDC_WPTSw8b1QFAKculeMztZAR0U',
    appId: '1:74152208737:ios:171fbb59af6598ff463d20',
    messagingSenderId: '74152208737',
    projectId: 'filmin-7e708',
    storageBucket: 'filmin-7e708.firebasestorage.app',
    iosBundleId: 'filmin.coop.filmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmzepmDC_WPTSw8b1QFAKculeMztZAR0U',
    appId: '1:74152208737:ios:171fbb59af6598ff463d20',
    messagingSenderId: '74152208737',
    projectId: 'filmin-7e708',
    storageBucket: 'filmin-7e708.firebasestorage.app',
    iosBundleId: 'filmin.coop.filmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0e2olAFDpmsUhe_HKbEf3Hj1oRqp3Vk',
    appId: '1:74152208737:web:639e5993b6535e72463d20',
    messagingSenderId: '74152208737',
    projectId: 'filmin-7e708',
    authDomain: 'filmin-7e708.firebaseapp.com',
    storageBucket: 'filmin-7e708.firebasestorage.app',
    measurementId: 'G-XS0MC538R1',
  );

}